Feature hero or
VOSolyanik/project-abovytan pull request #15
Opened 2024-10-03 20:45 UTC by OleksandrRyzhov2299

2024-10-03 21:58 UTC, VOSolyanik requested changes

2024-10-03 21:58 UTC, VOSolyanik commented on src/partials/hero.html
> +      <a class="hero-link" href="#">Leave an application</a>
hero-link -> btn btn-primary

2024-10-03 21:58 UTC, VOSolyanik commented on src/partials/hero.html
> +      <a class="hero-link" href="#">Leave an application</a>
href="#leave-application"

2024-10-03 21:58 UTC, VOSolyanik commented on src/css/sections/hero.css
> +  fill: currentColor;
icon is not visible

2024-10-03 21:58 UTC, VOSolyanik commented on src/css/sections/hero.css
> +.hero-wrapper {
hero-wrapper on desktop should be 1152px but now 1024

2024-10-03 21:58 UTC, VOSolyanik commented on src/css/sections/hero.css
> +.hero-wrapper {
use negative margin or set `.hero .container { paddong: 0 }`

2024-10-03 21:58 UTC, VOSolyanik commented on src/css/sections/hero.css
> +.hero-wrapper {
also please add for .header

.header { margin-bottom: 8px)

min-width: 768px 
    .header { margin-bottom: 32px)
    
min-width: 1152px 
    .header { margin-bottom: 16px)

2024-10-03 21:58 UTC, VOSolyanik commented on src/images/hero/bg_desk@2x.jpg
Images is not optimized

![Screenshot 2024-10-04 at 00 57 21](https://github.com/user-attachments/assets/6dd0d162-662d-47f6-904e-ea0d16e80573)
![Screenshot 2024-10-04 at 00 57 14](https://github.com/user-attachments/assets/fa057b9e-bd87-42ee-a4d7-62e12010b395)

2024-10-04 17:32 UTC, yuratouch commented on src/partials/hero.html
> +      <a class="hero-link" href="#">Leave an application</a>
fixed

2024-10-04 17:32 UTC, yuratouch commented on src/partials/hero.html
> +      <a class="hero-link" href="#">Leave an application</a>
fixed

2024-10-04 17:43 UTC, yuratouch commented on src/css/sections/hero.css
> +  fill: currentColor;
fixed

2024-10-04 18:28 UTC, yuratouch commented on src/css/sections/hero.css
> +.hero-wrapper {
all fixed

2024-10-04 18:28 UTC, yuratouch commented on src/images/hero/bg_desk@2x.jpg
images optimized. reduced 74% for jpg and 5% for webp

2024-10-04 18:30 UTC, yuratouch commented
![](https://github.trello.services/images/mini-trello-icon.png) [HC-12. Hero Section](https://trello.com/c/aIXZwIup/7-hc-12-hero-section)

2024-10-04 18:38 UTC, VOSolyanik approved these changes

2024-10-04 18:38 UTC, merged