HC-7. Add About Us section
VOSolyanik/project-abovytan pull request #4
Opened 2024-10-01 22:09 UTC by yuratouch

**1. src/css/common/base.css**
prettier форматування. Додав колір підкреслення. Додав напівпрозорий колір сірого тексту (.supporting-text). Видалив ресет значення (дублікуються з src/css/utils/reset.css). 

**2. src/css/common/container.css**
виправив значення відповідно до border-box моделі (додається на всі елементи з нормалайзера). Додав .extra-padding клас.

**3. src/css/common/section.css**
Додав загальні стилі для всіх секцій. Можна використовувати готові класи.

**4. src/css/sections/about-us.css**
Окремі стилі для About Us секції

**5. Картинки додав окремо під секцію. оптимізовані.**

2024-10-01 22:21 UTC, yuratouch commented
![](https://github.trello.services/images/mini-trello-icon.png) [HC-7. About us Section](https://trello.com/c/JJiS3Zpm/8-hc-7-about-us-section)

2024-10-02 05:47 UTC, VOSolyanik requested changes

2024-10-02 05:47 UTC, VOSolyanik commented on src/css/common/section.css
> +.supporting-text {
пропоную secondary-text або section-subheading

2024-10-02 05:47 UTC, VOSolyanik commented on src/css/common/section.css
> +  position: relative;
Краще absolute

2024-10-02 05:47 UTC, VOSolyanik commented on src/partials/about-us.html
> +      <li>
Ментор пропонував зробити це не лішкою, а типу about-us-list:after, бо це більше декоративний елемент ніж контентний

2024-10-02 07:10 UTC, yuratouch commented on src/css/common/section.css
> +.supporting-text {
Виправлено на .secondary-text

2024-10-02 07:13 UTC, yuratouch commented on src/css/common/section.css
> +  position: relative;
позиціонування змінив на абсолют

2024-10-02 08:23 UTC, yuratouch commented on src/partials/about-us.html
> +      <li>
Я трохи погрався з тим щоб переробити, спробував хоча б додати картинку для li:last-child як background-image. там є нюанс з ретіна картинкою. вона за розмірами більша і виглядає більшою ніж на дизайні. Загалом, воно виглядає нормально, центровано, але більша ніж на екрані. Тут потрібно щось з картинкою зробити мабуть, тому що ми маємо обмежений вплив на розмір фонового зображення. 
І стосовно переробки li:last-child на about-us-list:after. Це можна зробити, але там треба переробляти грід на флекс з обмеженими розмірами. загалом це можна зробити, але в звязці переформатуванням зображення це може зайняти суттєво часу. 
враховуючи що у нас залишається 2 дні до здачі роботи, а це поки що єдина готова секція, можливо є сенс поки що пропустити це як є, а потім вже зайнятись переробкою цього блоку як імпрувмент. 
А я би краще зайнявся іншими секціями, вроховуючи що у нас виходить мінімальна капасіті від учасників.

2024-10-02 08:28 UTC, yuratouch commented
Додатково додам коментар стосовно картинок. У VIte корректно додавати медіа все таки у папку public. Якщо додавати в images то при вкладеності файлів не вийде доступитись до неї. Наприклад, якщо ми хоче додати картинку фоному з css файлу. А з папки public двіжок VIte працює як треба і можна просто додавати url - images/hero/hero-banner.png (фактичний шлях public/images/hero/hero-banner.png)

2024-10-02 18:39 UTC, VOSolyanik approved these changes

2024-10-02 18:41 UTC, merged